version: "3.9"

services:
  ina-be-sim:
    container_name: akr-be
    build:
      context: .
      dockerfile: Dockerfile
    image: inaai-backend-sim:latest
    restart: always
    ports:
      - "4002:8000"
    command: poetry run start-server
    depends_on:
      - migration

  migration:
    container_name: ina-be-sim-migration
    build:
      context: .
      dockerfile: Dockerfile
    image: inaai-backend-sim:latest
    command: poetry run db-migrate
    restart: "no"
